#!/usr/bin/env bash
# Usage:
#   tests/integration
#
# Check the GitHub Actions output for expected output.
#
# To run this test suite you'll want to clone down this repo first since it
# depends on extracting information out of git to verify certain things like
# the --version command always stays in sync with the latest git tag.

set -o errexit
set -o pipefail
set -o nounset

DEBUG_TESTS="${DEBUG_TESTS:-}"

BMSU="src/bmsu"
BMSU_LATEST_GIT_TAG="$(git describe --tags --abbrev=0)"

TMP_DIR="/dev/shm"

# Something that is pretty much impossible to really exist.
INVALID_PATH="intergalactic-nocturnal-horse-radish"

readonly C_RED=$'\e[1;31;1m'
readonly C_GREEN=$'\e[1;32;1m'
readonly C_MAGENTA=$'\e[1;35;1m'
readonly C_CYAN=$'\e[1;36;1m'
readonly C_RESET=$'\e[0m'

readonly DEFAULT_PROFILE="${XDG_CONFIG_HOME}/bmsu/default"

readonly TEST_PROFILE_NAME="bmsu-test-profile"
readonly TEST_PROFILE="${DEFAULT_PROFILE/default/"${TEST_PROFILE_NAME}"}"

if [ -f "${DEFAULT_PROFILE}" ]; then
  mv "${DEFAULT_PROFILE}" "${DEFAULT_PROFILE}.bak"
fi

# -----------------------------------------------------------------------------
# Test helpers
# -----------------------------------------------------------------------------

cleanup() {
  if [ -f "${DEFAULT_PROFILE}.bak" ]; then
    mv "${DEFAULT_PROFILE}.bak" "${DEFAULT_PROFILE}"
  fi

  rm -rf "${TEST_PROFILE}" tmp
}

trap cleanup EXIT

_assert() {
  local match_type="${1}"
  local expected="${2}"

  shift 2

  printf "\n\n"

  # Capture all output, remove color and never fail at this point.
  local output
  output=$("${@}" 2>&1 | sed "s/\x1b\[[0-9;]*m//g") || true

  local full_output=""
  full_output=$(
    cat <<EOF
${C_CYAN}===============================================================================
FULL OUTPUT
===============================================================================${C_RESET}
${output}
${C_CYAN}===============================================================================${C_RESET}
EOF
  )

  local pass=false

  # Linux and macOS compatible multi-line regex search (replaces grep -Pz).
  #
  # -0777 "slurps" the entire output into one string for multi-line matching.
  #
  # -ne runs the following Perl code against the output
  #
  # exit(...):
  #   m{}   : use braces as delimiters so file paths (/) don't break the regex
  #   !     : flip Perl's "true" (1) to a Shell "success" (0)
  #   s     : modifier that allows the dot (.) to match newline characters
  if perl -0777 -ne "exit(!m{${expected}}s)" <<<"${output}"; then
    # Perl found a match and assert_output was called (! wasn't passed in).
    # We're looking for a match to pass.
    [ -z "${match_type}" ] && pass=1
  else
    # Perl didn't find a match and assert_no_output was called (! was passed in).
    # We're not looking (avoiding) a match to pass.
    [ "${match_type}" == "!" ] && pass=1
  fi

  if [ "${pass}" == "1" ]; then
    echo "${C_GREEN}PASS${C_RESET} :: ${C_MAGENTA}${*}${C_RESET} :: '${expected}'"

    if [ "${DEBUG_TESTS}" = "1" ]; then echo "${full_output}"; fi
  else
    echo "${C_RED}FAIL (LINE $(caller 1 | cut -d " " -f 1))${C_RESET} :: ${C_MAGENTA}${*}${C_RESET} :: '${expected}'"
    echo "${full_output}"

    exit 1
  fi
}

assert_output() {
  _assert "" "${@}"
}

assert_no_output() {
  _assert "!" "${@}"
}

edit_config() {
  local patterns=()

  for pattern in "${@}"; do
    patterns+=("-e" "${pattern};")
  done

  perl -pi "${patterns[@]}" "${TEST_PROFILE}"
}

# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------

assert_output "EXAMPLES" "${BMSU}" --help

assert_output "${BMSU_LATEST_GIT_TAG}" "${BMSU}" --version

assert_output ": ${BMSU_LATEST_GIT_TAG}" env BMSU_TEST_VALUE="0.4.0" "${BMSU}" --version-latest

assert_output ": Connection timed out" env BMSU_TEST_VALUE="curl: Connection timed out" "${BMSU}" --version-latest

assert_output "invalid-version-regex" env BMSU_TEST_VALUE="invalid-version-regex" "${BMSU}" --version-latest

echo "n" | assert_output "Would you like to update" env BMSU_TEST_VALUE="777.777.777" "${BMSU}" --version-latest

echo "y" | assert_output "Skipping" env BMSU_TEST_VALUE="777.777.777" "${BMSU}" --version-latest

assert_output "This appears to be the first time" "${BMSU}"

assert_output "BMSU_PROFILE: default" "${BMSU}" config

assert_output "--relative.*--cool.*--story" "${BMSU}" config --cool --story

assert_output "RSYNC_OPTIONS: '--no-relative' cannot be set" "${BMSU}" config --no-relative

assert_output "BMSU_DESTINATION: cannot be empty" "${BMSU}"

# Never operate on the default config and use a name that won't normally exist.
cp "${DEFAULT_PROFILE}" "${TEST_PROFILE}"
export BMSU_PROFILE="${TEST_PROFILE_NAME}"

assert_output "BMSU_PROFILE: ${TEST_PROFILE_NAME}" "${BMSU}" config

edit_config "s|^export BMSU_DEFAULT_RSYNC_OPTS=.*|export BMSU_DEFAULT_RSYNC_OPTS=(\"--hello\" \"--relative\")|"
assert_output "BMSU_DEFAULT_RSYNC_OPTS:\s*\n  \[0\] --hello" "${BMSU}" config

assert_output "Available profiles in " "${BMSU}" config list

assert_output "only 'example' is a supported argument" "${BMSU}" config show nope

assert_output "no arguments are supported" "${BMSU}" config diff nope

assert_output "no arguments are supported" "${BMSU}" config edit nope

assert_output "no arguments are supported" "${BMSU}" config delete nope

assert_output "DEBUG=" env BMSU_PROFILE= "${BMSU}" config show

assert_output "DEBUG=" "${BMSU}" config show example

assert_output "default config for bmsu" "${BMSU}" config diff

assert_output "'EDITOR' environment variable is not set" env EDITOR="" "${BMSU}" config edit

assert_output "'EDITOR=no-way-this-binary-exists' was not found" env EDITOR="no-way-this-binary-exists --wait" "${BMSU}" config edit

assert_output "DEBUG=" env EDITOR="cat" "${BMSU}" config edit

assert_output "missing profile name to create" env EDITOR="" "${BMSU}" config new

assert_output "DEBUG=" env EDITOR="cat" "${BMSU}" config new "${INVALID_PATH}"

assert_output "'${INVALID_PATH}' already exists" env EDITOR="cat" "${BMSU}" config new "${INVALID_PATH}"

echo "n" | assert_output "chosen not to delete" env BMSU_PROFILE="${INVALID_PATH}" "${BMSU}" config delete

echo "y" | assert_output "${TEST_PROFILE/${TEST_PROFILE_NAME}/${INVALID_PATH}}" env BMSU_PROFILE="${INVALID_PATH}" "${BMSU}" config delete

echo "y" | assert_output "'${INVALID_PATH}' does not exist" env BMSU_PROFILE="${INVALID_PATH}" "${BMSU}" config delete

edit_config "s|^export BMSU_DEFAULT_RSYNC_OPTS=.*|export BMSU_DEFAULT_RSYNC_OPTS=(\"-\")|"
assert_output "RSYNC_OPTIONS: '-' must start with" "${BMSU}"

edit_config "s|^export BMSU_DEFAULT_RSYNC_OPTS=.*|export BMSU_DEFAULT_RSYNC_OPTS=(\"--\")|"
assert_output "RSYNC_OPTIONS: '--' must start with" "${BMSU}"

edit_config "s|^export BMSU_DEFAULT_RSYNC_OPTS=.*|export BMSU_DEFAULT_RSYNC_OPTS=(\"--archive\")|"
assert_output "RSYNC_OPTIONS: '--relative' is missing" "${BMSU}"

edit_config "s|^export BMSU_DEFAULT_RSYNC_OPTS=.*|export BMSU_DEFAULT_RSYNC_OPTS=()|"
assert_output "BMSU_DESTINATION: cannot be empty" "${BMSU}"

edit_config \
  "s|^export BMSU_EXCLUDE_PATTERNS_EXTRAS=.*|export BMSU_EXCLUDE_PATTERNS_EXTRAS=(\"cool\")|" \
  "s|^export BMSU_EXCLUDE_PATTERNS_SKIP=.*|export BMSU_EXCLUDE_PATTERNS_SKIP=(\"*~\")|"
assert_output "BMSU_EXCLUDE_PATTERNS_EXTRAS:\n  \[\d\] cool" "${BMSU}" config
assert_no_output "BMSU_EXCLUDE_PATTERNS:\n  \[0] \*~" "${BMSU}" config

edit_config \
  "s|^export BMSU_EXCLUDE_PATTERNS_EXTRAS=.*|export BMSU_EXCLUDE_PATTERNS_EXTRAS=()|" \
  "s|^export BMSU_EXCLUDE_PATTERNS=.*|export BMSU_EXCLUDE_PATTERNS=|"
assert_output "BMSU_EXCLUDE_PATTERNS:\s*\n\n" "${BMSU}" config

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\"${TMP_DIR}/and/with/extra/paths/\"|"
assert_output "BMSU_DESTINATION: '${TMP_DIR}/and/with/extra/paths/' cannot end with a forward slash" "${BMSU}"

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\":~/\"|"
assert_output "BMSU_DESTINATION: ':~/' cannot end with a forward slash" "${BMSU}"

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\":badpath\"|"
assert_output "BMSU_DESTINATION: ':badpath' is an invalid format" "${BMSU}"

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\":~badpath\"|"
assert_output "BMSU_DESTINATION: ':~badpath' is an invalid format" "${BMSU}"

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\"${TMP_DIR}\"|"
assert_output "BMSU_SOURCES: cannot be empty" "${BMSU}"

edit_config "s|^export BMSU_SOURCES=.*|export BMSU_SOURCES=(\"tmp\")|"
assert_output "BMSU_SOURCES: 'tmp' must be an absolute path" "${BMSU}"

mkdir -p tmp

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\"tmp\"|"
assert_output "BMSU_DESTINATION: 'tmp' must be an absolute path" "${BMSU}"

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\"${TMP_DIR}/${INVALID_PATH}\"|"
assert_output "BMSU_DESTINATION: '${TMP_DIR}/${INVALID_PATH}' does not exist" "${BMSU}"

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\"/etc\"|"
assert_output "BMSU_DESTINATION: '/etc' has no valid external mount" "${BMSU}"

edit_config "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\"${TMP_DIR}\"|"
assert_output "BMSU_SOURCES: 'tmp' must be an absolute path" "${BMSU}"

edit_config "s|^export BMSU_SOURCES=.*|export BMSU_SOURCES=(\"${TMP_DIR}\")|"
assert_output "BMSU_SOURCES: '${TMP_DIR}' is identical to BMSU_DESTINATION='${TMP_DIR}'" "${BMSU}"

edit_config "s|^export BMSU_SOURCES=.*|export BMSU_SOURCES=(\"/${INVALID_PATH}\")|"
assert_output "BMSU_SOURCES: '/${INVALID_PATH}' does not exist" "${BMSU}"

edit_config "s|^export BMSU_SOURCES=.*|export BMSU_SOURCES=\"${TMP_DIR}/\"|"
assert_output "BMSU_SOURCES: '${TMP_DIR}/' cannot end with a forward slash" "${BMSU}"

edit_config \
  "s|^export BMSU_SOURCES=.*|export BMSU_SOURCES=(\"/var\")|" \
  "s|^export BMSU_DESTINATION=.*|export BMSU_DESTINATION=\"${TMP_DIR}\"|" \
  "s|^export BMSU_RESTORE_PATH=.*|export BMSU_RESTORE_PATH=|"
assert_output "BMSU_RESTORE_PATH: cannot be empty" "${BMSU}" restore

edit_config "s|^export BMSU_RESTORE_PATH=.*|export BMSU_RESTORE_PATH=\"${TMP_DIR}/\"|"
assert_output "BMSU_RESTORE_PATH: '${TMP_DIR}/' cannot end with a forward slash" "${BMSU}" restore

edit_config "s|^export BMSU_RESTORE_PATH=.*|export BMSU_RESTORE_PATH=\"tmp\"|"
assert_output "BMSU_RESTORE_PATH: 'tmp' must be an absolute" "${BMSU}" restore

edit_config "s|^export BMSU_RESTORE_PATH=.*|export BMSU_RESTORE_PATH=\"/${INVALID_PATH}\"|"
assert_output "BMSU_RESTORE_PATH: '/${INVALID_PATH}' does not exist" "${BMSU}" restore
