#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

readonly CONFIG_DIR="${XDG_CONFIG_HOME:-"${HOME}/.config"}/bmsu"
readonly DEFAULT_PROFILE="${CONFIG_DIR}/default"

readonly C_RED=$'\e[1;31;1m'
readonly C_GREEN=$'\e[1;32;1m'
readonly C_YELLOW=$'\e[1;33;1m'
readonly C_BLUE=$'\e[1;34;1m'
readonly C_MAGENTA=$'\e[1;35;1m'
readonly C_CYAN=$'\e[1;36;1m'
readonly C_RESET=$'\e[0m'

# -----------------------------------------------------------------------------
# Get the version
# -----------------------------------------------------------------------------
if [[ "${1:-}" =~ ^(-v|--version|version)$ ]]; then
  echo "0.1.0"
  exit
fi

# -----------------------------------------------------------------------------
# Present help
# -----------------------------------------------------------------------------
if [[ "${1:-}" =~ ^(-h|--help|help)$ ]]; then
  cat <<EOF
-------------------------------------------------------------------------------
TL;DR
-------------------------------------------------------------------------------

When running ${0} it depends on having a "profile", this has configuration such
as defining your source and destination paths, exclude patterns and more.

A default profile gets created for you and all custom profiles you create
inherit from this default. You can overwrite any values as desired.

Unless you're backing up to multiple destinations the default is all you need.

All profiles are saved in: ${CONFIG_DIR}

This script will never touch your profiles, if new configuration options get
introduced it's up to you to define them, check the changelog for these cases.

See https://github.com/nickjj/bmsu for details and to report issues.

-------------------------------------------------------------------------------
EXAMPLES
-------------------------------------------------------------------------------

# Perform a backup with the default profile.
${0}

# Pass 1 or more flags straight to rsync.
${0} --dry-run --delete

# Provide more output and requires typing 'y' to confirm before running it.
DEBUG=1 ${0}

# Instead of performing a backup, output the config being used.
${0} config

# Use a different profile other than the default.
BMSU_PROFILE=laptop ${0}
EOF

  exit
fi

# -----------------------------------------------------------------------------
# Ensure default profile is created before anything
# -----------------------------------------------------------------------------
create_default_profile() {
  # Never touch this file if it already exists.
  [ -f "${DEFAULT_PROFILE}" ] && return

  mkdir -p "${CONFIG_DIR}"

  cat <<EOF >"${DEFAULT_PROFILE}"
#!/usr/bin/env bash

set -o errexit

# Default to not using debug mode but allow running DEBUG=1 bmsu. If you
# want debug on by default set \${DEBUG-1} below. Even if it's enabled
# by default you can still run commands without it using DEBUG= bmsu.
export DEBUG="\${DEBUG-}"

# Flags and arguments that will get passed to rsync by default. If you leave
# this as is it will fallback to what the script internally defines.
#
# - Left as is OR commented out            -> default options get used
# - Remove () and set an empty value OR "" -> no options will get set
# - Add your own array items               -> only your options get used
#
# For example, if you don't like verbose mode you can set this:
#   BMSU_DEFAULT_RSYNC_OPTS=("--archive" "--relative")
export BMSU_DEFAULT_RSYNC_OPTS=()

# Where do you want the source paths to be sync'd to? This is your backup
# destination. The path must not end with a forward slash.
#
# For example, I have mine set to BMSU_DESTINATION=/data/backup/desktop and in
# this case /data/backup is a mount pointing to an external drive. Inside of
# that, the desktop directory is where my desktop machine's backups go.
#
# It can be a local mount, network mount or SSH path. If it's a mount, it must
# be an absolute path (starts with '/') or be a variable that resolves to one.
export BMSU_DESTINATION=

# Which paths do you want backed up? They must not end with a forward slash
# and all paths must be an absolute path or be a variable that resolves to one.
#
# It defaults to nothing, if you want ideas, here's what mine is set to:
# export BMSU_SOURCES=(
#   "\${HOME}/.config"
#   "\${HOME}/.docker/config.json"
#   "\${HOME}/.ssh"
#   "\${HOME}/src"
#   "/data/storage/docs"
#   "/data/storage/games/backups"
#   "/data/storage/media"
# )
export BMSU_SOURCES=()

# File and directory patterns that will get excluded. This avoids backing up
# cache, temporary and other generated files that exist in your source paths.
#
# All 3 variables below follow the same rules as BMSU_DEFAULT_RSYNC_OPTS for
# setting their values (keep it as is, empty or add in your own custom values).
#
# Unless you have a strong reason you'll probably only end up setting EXTRAS,
# in which case please open a PR if they're semi-general purpose patterns!
export BMSU_EXCLUDE_PATTERNS=()

# Append items to the default list.
export BMSU_EXCLUDE_PATTERNS_EXTRAS=()

# Remove items from the default list.
export BMSU_EXCLUDE_PATTERNS_SKIP=()
EOF

  cat <<EOF
This appears to be the first time you're running bmsu.

A default profile for you was just created at:

${DEFAULT_PROFILE}

You'll want to configure both BMSU_DESTINATION and BMSU_SOURCES in that file,
there's plenty of comments to get you going.

Also, you can run \`${0} --help\` to get help at any time.
EOF
  exit
}

show_config() {
  cat <<EOF
-------------------------------------------------------------------------------
FINAL CONFIG
-------------------------------------------------------------------------------
EOF

  for var in $(compgen -v "BMSU_"); do
    local -n value="${var}"
    local color=

    case "${var}" in
    "BMSU_DEFAULT_RSYNC_OPTS")
      color="${C_CYAN}"
      ;;
    "BMSU_DESTINATION")
      color="${C_MAGENTA}"
      ;;
    "BMSU_EXCLUDE_PATTERNS" | "BMSU_EXCLUDE_PATTERNS_EXTRAS" | "BMSU_EXCLUDE_PATTERNS_SKIP")
      color="${C_YELLOW}"
      ;;
    "BMSU_SOURCES")
      color="${C_GREEN}"
      ;;
    *)
      color="${C_BLUE}"
      ;;
    esac

    echo

    # Is the variable an array, also check to make sure it's not empty first.
    if [[ -n "${value+set}" && ${value@a} == *a* ]]; then
      echo "${color}${var}${C_RESET}:"

      for i in "${!value[@]}"; do
        echo "  [${i}] ${value[${i}]}"
      done
    else
      echo "${color}${var}${C_RESET}: ${value:-}"
    fi
  done

  echo
}

create_default_profile

#shellcheck disable=SC1090
. "${DEFAULT_PROFILE}"

# -----------------------------------------------------------------------------
# Select profile
# -----------------------------------------------------------------------------
BMSU_PROFILE="${BMSU_PROFILE:-}"

if [ -f "${CONFIG_DIR}/${BMSU_PROFILE}" ]; then
  # shellcheck disable=SC1090
  . "${CONFIG_DIR}/${BMSU_PROFILE}"
else
  if [ -z "${BMSU_PROFILE}" ]; then
    BMSU_PROFILE="default"
  else
    cat <<EOF >&2
${C_RED}BMSU_PROFILE${C_RESET}: '${BMSU_PROFILE}' does not exist, aborting!

If you want this profile to exist, create it at:

${CONFIG_DIR}/${BMSU_PROFILE}

Available profiles:

$(
      result=$(find "${CONFIG_DIR}" -type f | sort)
      echo "${result:-Only the default exists, avoid setting BMSU_PROFILE}"
    )
EOF

    exit 1
  fi
fi

# -----------------------------------------------------------------------------
# Set config values
# -----------------------------------------------------------------------------
if [[ "${BMSU_DEFAULT_RSYNC_OPTS+x}" ]]; then
  [ -z "${BMSU_DEFAULT_RSYNC_OPTS}" ] && BMSU_DEFAULT_RSYNC_OPTS=()
else
  BMSU_DEFAULT_RSYNC_OPTS=(
    "--archive"
    "--relative"
    "--verbose"
  )
fi

BMSU_DESTINATION="${BMSU_DESTINATION:-}"

if [[ "${BMSU_SOURCES+x}" ]]; then
  [ -z "${BMSU_SOURCES}" ] && BMSU_SOURCES=()
else
  BMSU_SOURCES=()
fi

if [[ "${BMSU_EXCLUDE_PATTERNS+x}" ]]; then
  [ -z "${BMSU_EXCLUDE_PATTERNS}" ] && BMSU_EXCLUDE_PATTERNS=()
else
  BMSU_EXCLUDE_PATTERNS=(
    "*~"
    ".asset-cache"
    ".bundle"
    ".jekyll-cache"
    ".pytest_cache"
    ".ruff_cache"
    ".tweet-cache"
    ".vagrant"
    "[._]*.s[a-v][a-z]"
    "[._]*.sw[a-p]"
    "[._]*.un~"
    "[._]s[a-rt-v][a-z]"
    "[._]ss[a-gi-z]"
    "[._]sw[a-p]"
    "__pycache__"
    "_site"
    "node_modules"
    "published"
    "tmp"
  )
fi

if [[ "${BMSU_EXCLUDE_PATTERNS_EXTRAS+x}" ]]; then
  [ -z "${BMSU_EXCLUDE_PATTERNS_EXTRAS}" ] && BMSU_EXCLUDE_PATTERNS_EXTRAS=()
else
  BMSU_EXCLUDE_PATTERNS_EXTRAS=()
fi

if [[ "${BMSU_EXCLUDE_PATTERNS_SKIP+x}" ]]; then
  [ -z "${BMSU_EXCLUDE_PATTERNS_SKIP}" ] && BMSU_EXCLUDE_PATTERNS_SKIP=()
else
  BMSU_EXCLUDE_PATTERNS_SKIP=()
fi

# -----------------------------------------------------------------------------
# Merge config values
# -----------------------------------------------------------------------------
merge_rsync_opts() {
  local -n default_rsync_opts="${1}"

  shift

  local rsync_opts_from_args=("${@}")

  # Known bmsu commands to skip processing.
  [ "${rsync_opts_from_args[0]:-}" == "config" ] && return

  default_rsync_opts+=("${rsync_opts_from_args[@]}")

  # Check to make sure all args (config and from the CLI) are flags, also
  # promote good habits by using the long form flag and = for values.
  for arg in "${default_rsync_opts[@]}"; do
    if [[ "${arg}" != -* || "${arg}" == "-" || "${arg}" == "--" ]]; then
      cat <<EOF >&2
${C_RED}RSYNC_OPTIONS${C_RESET}: '${arg:-[empty]}' must start with '-' and be a flag, aborting!

Tips:

- Use \`--bwlimit=RATE\` over \`--bwlimit RATE\` (set values with =)
- Prefer long flag names in general (human readability)
EOF
      exit 1
    fi
  done
}

merge_exclude_patterns() {
  local -n exclude_patterns="${1}"
  local -n exclude_patterns_extras="${2}"
  local -n exclude_patterns_skip="${3}"
  local exclude_patterns_filterd=()

  exclude_patterns+=("${exclude_patterns_extras[@]}")

  for pattern in "${exclude_patterns[@]}"; do
    for skip_pattern in "${exclude_patterns_skip[@]}"; do
      if [[ "${pattern}" == "${skip_pattern}" ]]; then
        # Continue the outer loop (the next pattern).
        continue 2
      fi
    done

    exclude_patterns_filterd+=("${pattern}")
  done

  exclude_patterns=("${exclude_patterns_filterd[@]}")
}

merge_rsync_opts "BMSU_DEFAULT_RSYNC_OPTS" "${@}"
merge_exclude_patterns "BMSU_EXCLUDE_PATTERNS" "BMSU_EXCLUDE_PATTERNS_EXTRAS" "BMSU_EXCLUDE_PATTERNS_SKIP"

# -----------------------------------------------------------------------------
# Maybe show the config after merging everything
# -----------------------------------------------------------------------------

if [[ "${DEBUG}" == "1" || "${1:-}" == "config" ]]; then
  show_config
  [ "${1:-}" == "config" ] && exit
fi

# These are populated below, we're doing it after the config to avoid them
# being included in the output since these are internal.
BMSU_MOUNT=
BMSU_DESTINATION_ABSOLUTE=
BMSU_SOURCE_ABSOLUTE=
BMSU_RSYNC_EXCLUDE_FLAGS=()
BMSU_RSYNC_SOURCES_FLAGS=()

BMSU_REMOTE=
BMSU_REMOTE_DESTINATION=
[[ "${BMSU_DESTINATION}" == *:* ]] && BMSU_REMOTE=1

# -----------------------------------------------------------------------------
# Validate destination
# -----------------------------------------------------------------------------
validate_destination() {
  if [ -z "${BMSU_DESTINATION}" ]; then
    cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: cannot be empty, set it in your config, aborting!

Your profile's config can be found at: ${BMSU_PROFILE}

There's a comment in the config file that has an example.
EOF

    exit 1
  fi

  if [[ "${BMSU_DESTINATION}" == */ ]]; then
    cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' cannot end with a forward slash, aborting!

This is to help protect us, rsync copies the entire directory without a slash
but if you have a slash only the contents of the directory are copied.
EOF

    exit 1
  fi

  # It's a remote path, not a mount.
  if [ "${BMSU_REMOTE}" == "1" ]; then
    BMSU_REMOTE_DESTINATION="${BMSU_DESTINATION#*:}"

    # rsync expands the ~/ user correctly with and without the user defined.
    # This effectively disables ~user which is supported by rsync but is not
    # as common as someone putting ~some/path while forgetting the slash.
    if [[ "${BMSU_REMOTE_DESTINATION}" != /* && "${BMSU_REMOTE_DESTINATION}" != \~/* && "${BMSU_REMOTE_DESTINATION}" != \~ ]]; then
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' is an invalid format, aborting!

Valid examples for what comes after the colon:

- Starts with / to be an absolute path
- Starts with ~/some/path
- ~ by itself to be the user's home directory

When '~' is used it will expand to the remote user if you supplied the user
as part of your destination, if not, it will use ${USER} (your local user).
EOF

      exit 1
    fi
    if [[ "${BMSU_DESTINATION}" == :* ]]; then
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' is missing at least a hostname, aborting!

Include the user@host or at least the host, for example:

${USER}@somehost${BMSU_DESTINATION}
somehost${BMSU_DESTINATION}
EOF
      exit 1
    fi
  else
    # It's a local or network mount, expand the user's home directory.
    BMSU_DESTINATION="${BMSU_DESTINATION/#~/${HOME}}"

    # Linux and macOS compatible way to get the mount path from a path.
    BMSU_MOUNT=$(df -P "${BMSU_DESTINATION}" 2>/dev/null | awk 'END{print $NF}' || true)

    if [ -z "${BMSU_MOUNT}" ]; then
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' does not exist, aborting!

Check your path for typos.
EOF

      exit 1
    fi

    if [ "${BMSU_MOUNT}" == "/" ]; then
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' has no valid external mount, aborting!

Here's the output of the \`mount\` command, check the above path or your mount below for typos:

$(mount)
EOF

      exit 1
    fi

    if [ ! -w "${BMSU_MOUNT}" ]; then
      # id -gn is used instead of $USER to report correctly on Linux and macOS.
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_MOUNT}' mount is not writable by ${USER} (your \$USER), aborting!

Here's the output of \`ls -lad ${BMSU_MOUNT}\` and a few tips:

$(ls -lad "${BMSU_MOUNT}")

The above line should start with 'drwx' and be owned by ${USER}:$(id -gn)

If the owner is root or another user, run:
  sudo chown -R ${USER}:$(id -gn) ${BMSU_MOUNT}

If you're missing write permissions (no 'w' in the first 4 chars), run:
  chmod -R u+w ${BMSU_MOUNT}

If all else fails run the \`mount "${BMSU_MOUNT}"\` command and confirm everything looks good.
EOF

      exit 1
    fi

    if [[ "${BMSU_DESTINATION}" != /* ]]; then
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' must be an absolute path, aborting!

It must start with '/' or be a variable that resolves to one.
EOF

      exit 1
    fi

    mkdir -p "${BMSU_DESTINATION}"
  fi
}

# -----------------------------------------------------------------------------
# Build up exclude patterns
# -----------------------------------------------------------------------------
validate_exclude_patterns() {
  for item in "${BMSU_EXCLUDE_PATTERNS[@]}"; do
    BMSU_RSYNC_EXCLUDE_FLAGS+=("--exclude=${item}")
  done
}

# -----------------------------------------------------------------------------
# Validate and build up sources
# -----------------------------------------------------------------------------
validate_sources() {
  if ((${#BMSU_SOURCES[@]} == 0)); then
    cat <<EOF >&2
${C_RED}BMSU_SOURCES${C_RESET}: cannot be empty, set it in your config, aborting!

Your profile's config can be found at: ${BMSU_PROFILE}

There's a comment in the config file that has an example.
EOF

    exit 1
  fi

  [ "${BMSU_REMOTE}" != "1" ] && BMSU_DESTINATION_ABSOLUTE=$(realpath "${BMSU_DESTINATION}")

  for item in "${BMSU_SOURCES[@]}"; do
    # Support expanding ~ to home.
    item="${item/#~/${HOME}}"

    # Check if it's a directory / file and readable.
    if [[ ! ((-d "${item}" || -f "${item}") && -r "${item}") ]]; then
      echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' is missing or not readable by ${USER}, aborting!" >&2
      exit 1
    fi

    if [[ "${item}" == */ ]]; then
      cat <<EOF >&2
${C_RED}BMSU_SOURCES${C_RESET}: '${item}' cannot end with a forward slash, aborting!

This is to help protect us, rsync copies the entire directory without a slash
but if you have a slash only the contents of the directory are copied.
EOF

      exit 1
    fi

    if [[ "${item}" != /* && "${item}" != *:* ]]; then
      echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' must be an absolute local or remote SSH path, aborting!" >&2
      exit 1
    fi

    # We can only run these tests for local or network mounts, not a remote path.
    if [ "${BMSU_REMOTE}" != "1" ]; then
      BMSU_SOURCE_ABSOLUTE=$(realpath "${item}")

      if [ "${BMSU_SOURCE_ABSOLUTE}" == "${BMSU_DESTINATION_ABSOLUTE}" ]; then
        echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' is identical to BMSU_DESTINATION='${BMSU_DESTINATION}', aborting!" >&2
        exit 1
      fi

      if [[ "${BMSU_DESTINATION_ABSOLUTE}" == "${BMSU_SOURCE_ABSOLUTE}/"* ]]; then
        echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' is a parent of BMSU_DESTINATION='${BMSU_DESTINATION}', aborting!" >&2
        exit 1
      fi

      if [[ "${BMSU_SOURCE_ABSOLUTE}" == "${BMSU_DESTINATION_ABSOLUTE}/"* ]]; then
        echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' is inside BMSU_DESTINATION='${BMSU_DESTINATION}', aborting!" >&2
        exit 1
      fi
    fi

    BMSU_RSYNC_SOURCES_FLAGS+=("${item}")
  done
}

# -----------------------------------------------------------------------------
# Prepare rsync command
# -----------------------------------------------------------------------------
prepare_rsync_command() {
  # Ensure each string and array element is colored up but not the backslashes.
  PRETTY_COMMAND=("${C_BLUE}rsync${C_RESET}"
    "${BMSU_DEFAULT_RSYNC_OPTS[@]/#/$C_CYAN}"
    "${BMSU_RSYNC_EXCLUDE_FLAGS[@]/#/$C_YELLOW}"
    "${BMSU_RSYNC_SOURCES_FLAGS[@]/#/$C_GREEN}"
    "${C_MAGENTA}${BMSU_DESTINATION}${C_RESET}")
  PRETTY_COMMAND=("${PRETTY_COMMAND[@]/%/$C_RESET}")

  COMMAND=(rsync
    "${BMSU_DEFAULT_RSYNC_OPTS[@]}"
    "${BMSU_RSYNC_EXCLUDE_FLAGS[@]}"
    "${BMSU_RSYNC_SOURCES_FLAGS[@]}"
    "${BMSU_DESTINATION}")
}

# -----------------------------------------------------------------------------
# Debug information
# -----------------------------------------------------------------------------
print_debug_info() {
  cat <<EOF
-------------------------------------------------------------------------------
FINAL RSYNC COMMAND
-------------------------------------------------------------------------------

EOF

  # Pretty print the arguments. The sed command is adding 2 spaces before each
  # argument except the first one and strips the last trailing slash. It's done
  # in a way that works on Linux and macOS.
  for arg in "${PRETTY_COMMAND[@]}"; do
    # Backslash escaping fun, this yields (1) printed backslash.
    printf "%b \\\\\n" "${arg}"
  done | sed -e "1b" -e "s/^/  /" -e '$ s/ \\$//'

  while true; do
    printf "\nTo run the above command, type 'y' and press enter (y/n) "
    read -r yn

    case "${yn}" in
    [Yy]*)
      break
      ;;
    [Nn]*) exit ;;
    *) printf "Please answer y or n\n" ;;
    esac
  done

  cat <<EOF

-------------------------------------------------------------------------------
RSYNC OUTPUT
-------------------------------------------------------------------------------

EOF
}

validate_destination
validate_exclude_patterns
validate_sources
prepare_rsync_command
[ "${DEBUG}" == "1" ] && print_debug_info

# Finally, let's run rsync!
time "${COMMAND[@]}"
