#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

readonly SCRIPT_VERSION="0.5.1"
readonly SCRIPT_NAME="${0##*/}"

readonly CONFIG_DIR="${XDG_CONFIG_HOME:-"${HOME}/.config"}/bmsu"
readonly DEFAULT_PROFILE="${CONFIG_DIR}/default"

readonly C_RED=$'\e[1;31;1m'
readonly C_GREEN=$'\e[1;32;1m'
readonly C_YELLOW=$'\e[1;33;1m'
readonly C_BLUE=$'\e[1;34;1m'
readonly C_MAGENTA=$'\e[1;35;1m'
readonly C_CYAN=$'\e[1;36;1m'
readonly C_WHITE=$'\e[1;37;1m'
readonly C_RESET=$'\e[0m'

CONFIG_DEBUG="$(
  cat <<EOF
# Default to not using debug mode but allow running DEBUG=1 bmsu. If you
# want debug on by default set \${DEBUG-1} below. Even if it's enabled
# by default you can still run commands without it using DEBUG= bmsu.
export DEBUG="\${DEBUG-}"
EOF
)"

CONFIG_BMSU_DEFAULT_RSYNC_OPTS="$(
  cat <<EOF
# Flags and arguments that will get passed to rsync by default. If you leave
# this as is it will fallback to what the script internally defines.
#
# - Left as is OR commented out            -> default options get used
# - Remove () and set an empty value OR "" -> no options will get set
# - Add your own array items               -> only your options get used
#
# Both the "extras" and "skip" variables let you modify the internal defaults
# without needing to redefine every option.
export BMSU_DEFAULT_RSYNC_OPTS=()
EOF
)"

CONFIG_BMSU_DEFAULT_RSYNC_OPTS_EXTRAS="$(
  cat <<EOF
# Append items to the default list.
export BMSU_DEFAULT_RSYNC_OPTS_EXTRAS=()
EOF
)"

CONFIG_BMSU_DEFAULT_RSYNC_OPTS_SKIP="$(
  cat <<EOF
# Remove items from the default list.
export BMSU_DEFAULT_RSYNC_OPTS_SKIP=()
EOF
)"

CONFIG_BMSU_DESTINATION="$(
  cat <<EOF
# Where do you want the source paths to be sync'd to? This is your backup
# destination. The path must not end with a forward slash.
#
# For example, I have mine set to BMSU_DESTINATION=/data/backup/desktop and in
# this case /data/backup is a mount pointing to an external drive. Inside of
# that, the desktop directory is where my desktop machine's backups go.
#
# It can be a local mount, network mount or SSH path. If it's a mount, it must
# be an absolute path (starts with '/') or be a variable that resolves to one.
export BMSU_DESTINATION=
EOF
)"

CONFIG_BMSU_SOURCES="$(
  cat <<EOF
# Which paths do you want backed up? They must not end with a forward slash
# and all paths must be an absolute path or be a variable that resolves to one.
#
# It defaults to nothing, if you want ideas, here's what mine is set to:
#
# export BMSU_SOURCES=(
#   "\${HOME}/.config"
#   "\${HOME}/.docker/config.json"
#   "\${HOME}/.ssh"
#   "\${HOME}/src"
#   "/data/storage/docs"
#   "/data/storage/games/backups"
#   "/data/storage/media"
# )
export BMSU_SOURCES=()
EOF
)"

CONFIG_BMSU_EXCLUDE_PATTERNS="$(
  cat <<EOF
# File and directory patterns that will get excluded. This avoids backing up
# cache, temporary and other generated files that exist in your source paths.
#
# All 3 variables below follow the same rules as BMSU_DEFAULT_RSYNC_OPTS for
# setting their values (keep it as is, empty or add in your own custom values)
# and how appending or removing items works.
#
# Unless you have a strong reason you'll probably only end up setting EXTRAS,
# in which case please open a PR if they're semi-general purpose patterns!
export BMSU_EXCLUDE_PATTERNS=()
EOF
)"

CONFIG_BMSU_EXCLUDE_PATTERNS_EXTRAS="$(
  cat <<EOF
# Append items to the default list.
export BMSU_EXCLUDE_PATTERNS_EXTRAS=()
EOF
)"

CONFIG_BMSU_EXCLUDE_PATTERNS_SKIP="$(
  cat <<EOF
# Remove items from the default list.
export BMSU_EXCLUDE_PATTERNS_SKIP=()
EOF
)"

CONFIG_BMSU_RESTORE_PATH="$(
  cat <<EOF
# This remains unused unless you run \`bmsu restore\`.
#
# When you're ready to restore, you'll usually want to set it to "/", since
# --relative is always used rsync knows to create your source paths where they
# should be. For testing you can use "/tmp" to see which files really get restored.
#
# Tip: you can use the rsync --update flag to avoid overwriting newer files
# that exist on your source. Be careful with --delete too!
#
# Debug mode is always enabled for it, there's also --dry-run and temporarily
# using "/tmp" to verify your paths before you perform your restore on "/".
#
# P.S., the special /./ path you'll see in the final rsync command configures
# rsync to only restore the path to the right of it, this avoids copying your
# BMSU_DESTINATION as part of the restore path.
export BMSU_RESTORE_PATH=
EOF
)"

CONFIG_DEFAULT="$(
  cat <<EOF
#!/usr/bin/env bash

${CONFIG_DEBUG}

${CONFIG_BMSU_DEFAULT_RSYNC_OPTS}

${CONFIG_BMSU_DEFAULT_RSYNC_OPTS_EXTRAS}

${CONFIG_BMSU_DEFAULT_RSYNC_OPTS_SKIP}

${CONFIG_BMSU_DESTINATION}

${CONFIG_BMSU_SOURCES}

${CONFIG_BMSU_EXCLUDE_PATTERNS}

${CONFIG_BMSU_EXCLUDE_PATTERNS_EXTRAS}

${CONFIG_BMSU_EXCLUDE_PATTERNS_SKIP}

${CONFIG_BMSU_RESTORE_PATH}
EOF
)"

# -----------------------------------------------------------------------------
# Get the version
# -----------------------------------------------------------------------------
if [[ "${1:-}" =~ ^(-v|--version|version)$ ]]; then
  echo "${SCRIPT_VERSION}"
  exit
fi

# -----------------------------------------------------------------------------
# Get the latest version and maybe update
# -----------------------------------------------------------------------------
version_latest() {
  local url="https://raw.githubusercontent.com/nickjj/bmsu/main/src/bmsu"
  local result=

  # This is an undocumented feature to make it easier to test this function
  # without creating a mock for curl. Not a fan of this but it works.
  if [ -n "${BMSU_TEST_VALUE:-}" ]; then
    result="${BMSU_TEST_VALUE}"
  else
    # Returns back either the version number or an error by curl which
    # starts with "curl", we want result= to contain either or.
    result=$(curl --fail --silent --show-error --location --max-time 5 "${url}" 2>&1 |
      sed -n '/^readonly SCRIPT_VERSION=/ s/.*"\(.*\)".*/\1/p; /^curl/p') || true
  fi

  if [[ ! "${result}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    cat <<EOF >&2
${C_RED}CURL${C_RESET}: unable to check the latest release, aborting!

Reason: ${result:-"Unknown (curl returned no information)"}

Check the latest version at: https://github.com/nickjj/bmsu/blob/main/CHANGELOG.md
EOF

    exit 1
  fi

  printf "Latest version: %s\n  Your version: %s\n" "${result}" "${SCRIPT_VERSION}"

  [ "${result}" == "${SCRIPT_VERSION}" ] && return

  while true; do
    printf "\nWould you like to update to the latest version? (y/n) "
    read -r yn

    case "${yn}" in
    [Yy]*) break ;;
    [Nn]*) exit ;;
    *) printf "Please answer y or n\n" ;;
    esac
  done

  local bmsu_path=
  bmsu_path="$(realpath "${0}")"

  if [[ "${bmsu_path}" == *"src/bmsu"* ]]; then
    printf "\nSkipping, since this looks like a development version of bmsu.\n"
    return
  fi

  local download_path=
  download_path="$(mktemp)"

  # Make sure we download the tagged version instead of from the main branch.
  url="${url/\/main\//\/${result}\/}"

  local download_result=
  if ! download_result=$(curl --fail --silent --show-error --location --max-time 5 --output "${download_path}" "${url}" 2>&1); then
    cat <<EOF >&2

${C_RED}CURL${C_RESET}: unable to download the latest version, aborting!

Reason: ${download_result:-"Unknown (curl returned no information)"}

Download the latest version at: https://github.com/nickjj/bmsu
EOF
    exit 1
  fi

  chmod +x "${download_path}"

  cat <<EOF

${C_GREEN}UPDATE${C_RESET}: success, you can run bmsu to start using ${result}!

Check the changelog to see what's new: https://github.com/nickjj/bmsu/blob/main/CHANGELOG.md
EOF

  mv "${download_path}" "${bmsu_path}"
}

if [[ "${1:-}" =~ ^(-V|--version-latest|version-latest)$ ]]; then
  version_latest
  exit
fi

# -----------------------------------------------------------------------------
# Present help
# -----------------------------------------------------------------------------
if [[ "${1:-}" =~ ^(-h|--help|help)$ ]]; then
  cat <<EOF
-------------------------------------------------------------------------------
TL;DR
-------------------------------------------------------------------------------

When running ${SCRIPT_NAME} it depends on having a "profile", this has configuration such
as defining your source and destination paths, exclude patterns and more.

A default profile gets created for you and all custom profiles you create
inherit from this default. You can overwrite any values as desired.

Unless you're backing up to multiple destinations or syncing files between
multiple devices (desktop, laptop, phone, etc.) the default is all you need.

All profiles are saved in: ${CONFIG_DIR}

This script will never auto-edit your profiles, if any configuration options
change then bmsu will let you know when you try to run a backup or restore.

See https://github.com/nickjj/bmsu for documentation and to report issues.

-------------------------------------------------------------------------------
EXAMPLES
-------------------------------------------------------------------------------

# Perform a backup with the default profile.
${SCRIPT_NAME}

# Pass 1 or more flags straight to rsync.
${SCRIPT_NAME} --dry-run --delete

# Provide more output and requires typing 'y' to confirm before running it.
DEBUG=1 ${SCRIPT_NAME}

# Instead of performing a backup, output your profile's config being used.
${SCRIPT_NAME} config

# Use a different profile other than the default.
BMSU_PROFILE=laptop ${SCRIPT_NAME}

# Perform a restore but avoid clobbering newer files that exist on your source system.
${SCRIPT_NAME} restore --update

-------------------------------------------------------------------------------
CONFIG MANAGEMENT
-------------------------------------------------------------------------------

# List all of your profile configs.
bmsu config list

# Show your profile's config, supports BMSU_PROFILE.
bmsu config show

# Show the default profile config for your downloaded version of bmsu.
${SCRIPT_NAME} config show example

# Diff your profile config vs the example profile config. Supports BMSU_PROFILE.
${SCRIPT_NAME} config diff

# Edit your profile's config, supports BMSU_PROFILE.
${SCRIPT_NAME} config edit

# Create a new profile config and then edit it.
bmsu config new PROFILE_NAME

# Delete your profile's config, supports BMSU_PROFILE.
bmsu config delete

-------------------------------------------------------------------------------
BMSU DETAILS
-------------------------------------------------------------------------------

# Show the version you have currently.
bmsu --version

# Show the latest version and offer to update if a newer version exists.
bmsu --version-latest

# Show the help.
bmsu --help
EOF

  exit
fi

# -----------------------------------------------------------------------------
# Ensure default profile is created before anything
# -----------------------------------------------------------------------------
create_default_profile() {
  # Never touch this file if it already exists.
  [ -f "${DEFAULT_PROFILE}" ] && return

  mkdir -p "${CONFIG_DIR}"
  echo "${CONFIG_DEFAULT}" >"${DEFAULT_PROFILE}"

  cat <<EOF
This appears to be the first time you're running bmsu.

A default profile for you was just created in: ${CONFIG_DIR}

You'll want to configure both BMSU_DESTINATION and BMSU_SOURCES in that file,
there's plenty of comments to get you going.

Also, you can run \`${SCRIPT_NAME} --help\` to get help at any time.
EOF
  exit
}

# -----------------------------------------------------------------------------
# Config commands
# -----------------------------------------------------------------------------
print_config() {
  cat <<EOF
-------------------------------------------------------------------------------
FINAL CONFIG
-------------------------------------------------------------------------------
EOF

  for var in $(compgen -v "BMSU_"); do
    local -n value="${var}"
    local color=

    case "${var}" in
    "BMSU_DEFAULT_RSYNC_OPTS" | "BMSU_DEFAULT_RSYNC_OPTS_EXTRAS" | "BMSU_DEFAULT_RSYNC_OPTS_SKIP")
      color="${C_CYAN}"
      ;;
    "BMSU_DESTINATION" | "BMSU_RESTORE_PATH")
      color="${C_MAGENTA}"
      ;;
    "BMSU_EXCLUDE_PATTERNS" | "BMSU_EXCLUDE_PATTERNS_EXTRAS" | "BMSU_EXCLUDE_PATTERNS_SKIP")
      color="${C_YELLOW}"
      ;;
    "BMSU_SOURCES")
      color="${C_GREEN}"
      ;;
    *)
      color="${C_BLUE}"
      ;;
    esac

    echo

    # Is the variable an array, also check to make sure it's not empty first.
    if [[ -n "${value+set}" && ${value@a} == *a* ]]; then
      echo "${color}${var}${C_RESET}:"

      for i in "${!value[@]}"; do
        echo "  [${i}] ${value[${i}]}"
      done
    else
      echo "${color}${var}${C_RESET}: ${value:-}"
    fi
  done

  echo
}

config_list() {
  printf "Available profiles in '%s'\n\n" "${CONFIG_DIR}"

  # We live the good life, let's try and see if eza is available first.
  if command -v eza >/dev/null 2>&1; then
    EZA_ICON_SPACING=2 eza --long --all --octal-permissions \
      --group --group-directories-first --time-style long-iso \
      --header --icons auto "${CONFIG_DIR}"
  else
    # shellcheck disable=SC2012
    ls -lAF "${CONFIG_DIR}" | sed "/^total/d"
  fi
}

config_show() {
  local profile="${1:-}"
  local content

  case "${profile}" in
  "")
    content=$(<"${CONFIG_DIR}/${BMSU_PROFILE}")
    ;;
  "example")
    content="${CONFIG_DEFAULT}"
    ;;
  *)
    cat <<EOF >&2
${C_RED}ARGUMENT${C_RESET}: only 'example' is a supported argument, aborting!

If you want to view this config, run this:

${SCRIPT_NAME} BMSU_PROFILE='${profile}' config
EOF
    exit 1
    ;;
  esac

  # We live the good life, let's try and see if bat is available first.
  if command -v bat >/dev/null 2>&1; then
    bat --paging=never --style=plain <<<"${content}"
  else
    echo "${content}"
  fi
}

config_diff() {
  local profile="${1:-}"
  local default_label="default config for ${SCRIPT_NAME} ${SCRIPT_VERSION}"
  local profile_path="${CONFIG_DIR}/${BMSU_PROFILE}"

  if [ -n "${profile}" ]; then
    cat <<EOF >&2
${C_RED}ARGUMENT${C_RESET}: no arguments are supported, aborting!

If you want to diff this config, run this:

${SCRIPT_NAME} BMSU_PROFILE='${profile}' config
EOF
    exit 1
  fi

  # We live the good life, let's try and see if delta is available first.
  # Also we want nice labels and macOS' version of diff doesn't support color
  # by default so we can roll our own in a cross OS compatible way.
  { diff -u -L "${default_label}" -L "${profile_path}" \
    <(echo "${CONFIG_DEFAULT}") "${profile_path}" || true; } |
    if command -v delta >/dev/null 2>&1; then
      DELTA_FEATURES="diff-so-fancy" delta --paging=never
    else
      sed "s/^-/${C_RED}-/g; s/^+/${C_GREEN}+/g; s/^@/${C_CYAN}@/g; s/$/${C_RESET}/g"
    fi
}

# shellcheck disable=SC2120
config_edit() {
  local profile="${1:-}"

  if [ -n "${profile}" ]; then
    cat <<EOF >&2
${C_RED}ARGUMENT${C_RESET}: no arguments are supported, aborting!

If you want to edit this config, run this:

${SCRIPT_NAME} BMSU_PROFILE='${profile}' config
EOF
    exit 1
  fi

  if [ -z "${EDITOR:-}" ]; then
    cat <<EOF >&2
${C_RED}EDITOR${C_RESET}: 'EDITOR' environment variable is not set, aborting!

It's a Unix convention to set it so programs know which editor to open by default.

If you have vim, nano or another common editor installed, try running:

EDITOR=vim ${SCRIPT_NAME} config edit

You can persist this in your shell's rc file (bash, zsh, etc.) by adding:

export EDITOR="vim"

Replace "vim" with your editor's command, such as "nvim", "code", "subl", "nano", etc..

If you have certain graphical editors like code, subl or others it's a good
idea to also set them to wait, it's common for it to be the --wait flag but
you can check your editor's --help for details.

In which case you would set this instead:

export EDITOR="code --wait"

This script doesn't require this behavior but other scripts might want to wait
until you've completed editing a file before continuing.

Editors like nvim, vim and nano don't need this because they open directly
in your shell's session and after exiting, the script knows when to resume.

Once you've saved your rc file, open a new terminal session and re-run: ${SCRIPT_NAME} config edit
EOF

    exit 1
  fi

  # In case it has flags (--wait, etc.), only return the binary name.
  local editor_binary="${EDITOR%% *}"

  if ! command -v "${editor_binary}" >/dev/null 2>&1; then
    cat <<EOF >&2
${C_RED}EDITOR${C_RESET}: 'EDITOR=${editor_binary}' was not found, aborting!

Make sure it's on available on your system path. You need it to be directly
callable from your shell. If you can't, it's not on your path. Check your
editor's documentation for details.

Usually it means making sure its binary is in /usr/local/bin or ~/.local/bin
and those paths would be set in your PATH which is configured in your shell's
profile or rc file.

You can check your path by running: echo \${PATH}

For example, here's your \$PATH:

${PATH}
EOF
    exit 1
  fi

  ${EDITOR} "${CONFIG_DIR}/${BMSU_PROFILE}"
}

config_new() {
  local profile="${1:-}"
  local profile_path="${CONFIG_DIR}/${profile}"

  if [ -z "${profile}" ]; then
    echo "${C_RED}ARGUMENT${C_RESET}: missing profile name to create, aborting!" >&2
    exit 1
  fi

  if [ -f "${profile_path}" ]; then
    echo "${C_RED}ARGUMENT${C_RESET}: '${profile}' already exists, aborting!" >&2
    exit 1
  fi

  echo "${CONFIG_DEFAULT}" >"${profile_path}"

  BMSU_PROFILE="${profile}" config_edit
}

config_delete() {
  local profile="${1:-}"
  local profile_path="${CONFIG_DIR}/${BMSU_PROFILE}"

  if [ -n "${profile}" ]; then
    cat <<EOF >&2
${C_RED}ARGUMENT${C_RESET}: no arguments are supported, aborting!

If you want to delete this config, run this:

${SCRIPT_NAME} BMSU_PROFILE='${profile}' config
EOF
    exit 1
  fi

  print_config

  echo "Config path: ${profile_path}"

  printf "\nAre you sure you want to delete the above config? (y/n) "
  read -r yn
  if [[ ! ${yn} =~ ^[Yy]$ ]]; then
    printf "\nYou've chosen not to delete it, aborting!\n" >&2
    exit 1
  fi

  if [ ! -f "${profile_path}" ]; then
    cat <<EOF >&2
${C_RED}ARGUMENT${C_RESET}: '${profile_path}' does not exist, aborting!

Check your path for typos.

EOF
    exit 1
  fi

  rm -f "${profile_path}"
}

create_default_profile

#shellcheck disable=SC1090
. "${DEFAULT_PROFILE}"

# -----------------------------------------------------------------------------
# Select profile
# -----------------------------------------------------------------------------
BMSU_PROFILE="${BMSU_PROFILE:-}"

if [ -f "${CONFIG_DIR}/${BMSU_PROFILE}" ]; then
  # shellcheck disable=SC1090
  . "${CONFIG_DIR}/${BMSU_PROFILE}"
else
  if [ -z "${BMSU_PROFILE}" ]; then
    BMSU_PROFILE="default"
  else
    cat <<EOF >&2
${C_RED}BMSU_PROFILE${C_RESET}: '${BMSU_PROFILE}' does not exist, aborting!

If you want this profile to exist, create it at: ${CONFIG_DIR}/${BMSU_PROFILE}

EOF
    config_list

    exit 1
  fi
fi

# -----------------------------------------------------------------------------
# Set config values
# -----------------------------------------------------------------------------
if [[ "${BMSU_DEFAULT_RSYNC_OPTS+x}" ]]; then
  [ -z "${BMSU_DEFAULT_RSYNC_OPTS}" ] && BMSU_DEFAULT_RSYNC_OPTS=()
else
  BMSU_DEFAULT_RSYNC_OPTS=(
    "--archive"
    "--relative"
    "--verbose"
  )
fi

if [[ "${BMSU_DEFAULT_RSYNC_OPTS_EXTRAS+x}" ]]; then
  [ -z "${BMSU_DEFAULT_RSYNC_OPTS_EXTRAS}" ] && BMSU_DEFAULT_RSYNC_OPTS_EXTRAS=()
else
  BMSU_DEFAULT_RSYNC_OPTS_EXTRAS=()
fi

if [[ "${BMSU_DEFAULT_RSYNC_OPTS_SKIP+x}" ]]; then
  [ -z "${BMSU_DEFAULT_RSYNC_OPTS_SKIP}" ] && BMSU_DEFAULT_RSYNC_OPTS_SKIP=()
else
  BMSU_DEFAULT_RSYNC_OPTS_SKIP=()
fi

BMSU_DESTINATION="${BMSU_DESTINATION:-}"

if [[ "${BMSU_SOURCES+x}" ]]; then
  [ -z "${BMSU_SOURCES}" ] && BMSU_SOURCES=()
else
  BMSU_SOURCES=()
fi

if [[ "${BMSU_EXCLUDE_PATTERNS+x}" ]]; then
  [ -z "${BMSU_EXCLUDE_PATTERNS}" ] && BMSU_EXCLUDE_PATTERNS=()
else
  BMSU_EXCLUDE_PATTERNS=(
    "*~"
    ".asset-cache"
    ".bundle"
    ".jekyll-cache"
    ".pytest_cache"
    ".ruff_cache"
    ".tweet-cache"
    ".vagrant"
    "[._]*.s[a-v][a-z]"
    "[._]*.sw[a-p]"
    "[._]*.un~"
    "[._]s[a-rt-v][a-z]"
    "[._]ss[a-gi-z]"
    "[._]sw[a-p]"
    "__pycache__"
    "_site"
    "node_modules"
    "published"
    "tmp"
  )
fi

if [[ "${BMSU_EXCLUDE_PATTERNS_EXTRAS+x}" ]]; then
  [ -z "${BMSU_EXCLUDE_PATTERNS_EXTRAS}" ] && BMSU_EXCLUDE_PATTERNS_EXTRAS=()
else
  BMSU_EXCLUDE_PATTERNS_EXTRAS=()
fi

if [[ "${BMSU_EXCLUDE_PATTERNS_SKIP+x}" ]]; then
  [ -z "${BMSU_EXCLUDE_PATTERNS_SKIP}" ] && BMSU_EXCLUDE_PATTERNS_SKIP=()
else
  BMSU_EXCLUDE_PATTERNS_SKIP=()
fi

BMSU_RESTORE_PATH="${BMSU_RESTORE_PATH:-}"

# -----------------------------------------------------------------------------
# Validation helpers
# -----------------------------------------------------------------------------
_invalid_config_help() {
  local variable_name="${1}"
  local example_name="CONFIG_${variable_name}"

  cat <<EOF >&2
Your profile's config can be found at: ${CONFIG_DIR}/${BMSU_PROFILE}

Here's an example of how to set ${variable_name}:

---

${!example_name}

---

Tips:

- Run \`${SCRIPT_NAME} config example\` to see the default profile config
- Run \`${SCRIPT_NAME} config diff\` to diff your config vs the latest config
EOF
}

_validate_config_presence() {
  local variable_name="${1}"

  if [[ -z ${!variable_name+x} ]] || [[ -z ${!variable_name} ]]; then
    cat <<EOF >&2
${C_RED}${variable_name}${C_RESET}: cannot be empty, set it in your config, aborting!

EOF

    _invalid_config_help "${variable_name}"
    exit 1
  fi
}

_validate_config_array() {
  local variable_name="${1}"

  if [[ ! ${!variable_name@a} == *a* ]]; then
    cat <<EOF >&2
${C_RED}${variable_name}${C_RESET}: must be an array (not string), aborting!

EOF

    _invalid_config_help "${variable_name}"
    exit 1
  fi
}

_validate_config_string() {
  local variable_name="${1}"

  if [[ ${!variable_name@a} == *a* ]]; then
    cat <<EOF >&2
${C_RED}${variable_name}${C_RESET}: must be a string (not array), aborting!

EOF

    _invalid_config_help "${variable_name}"
    exit 1
  fi
}

_validate_absolute_path() {
  local variable_name="${1}"

  if [ "${2:-}" ]; then
    local variable_reference="${2}"
  else
    local -n variable_reference="${variable_name}"
  fi

  if [[ "${variable_reference}" != /* ]]; then
    cat <<EOF >&2
${C_RED}${variable_name}${C_RESET}: '${variable_reference}' must be an absolute path, aborting!

It must start with '/' or be a variable that resolves to one.

EOF

    _invalid_config_help "${variable_name}"
    exit 1
  fi
}

_validate_no_ending_forward_slash() {
  local variable_name="${1}"

  if [ "${2:-}" ]; then
    local variable_reference="${2}"
  else
    local -n variable_reference="${variable_name}"
  fi

  if [[ "${variable_reference}" == */ ]]; then
    cat <<EOF >&2
${C_RED}${variable_name}${C_RESET}: '${variable_reference}' cannot end with a forward slash, aborting!

This is to help protect us, rsync copies the entire directory without a slash
but if you have a slash only the contents of the directory are copied.

EOF

    _invalid_config_help "${variable_name}"
    exit 1
  fi
}

_validate_path_exists() {
  local variable_name="${1}"
  local -n variable_reference="${variable_name}"

  if [ "${2:-}" ]; then
    local variable_reference="${2}"
  else
    local -n variable_reference="${variable_name}"
  fi

  cat <<EOF >&2
${C_RED}${variable_name}${C_RESET}: '${variable_reference}' does not exist, aborting!

Check your path for typos.

EOF

  _invalid_config_help "${variable_name}"
  exit 1
}

# -----------------------------------------------------------------------------
# Merge config values
# -----------------------------------------------------------------------------
merge_rsync_opts() {
  local -n default_rsync_opts="${1}"
  local -n default_rsync_opts_extras="${2}"
  local -n default_rsync_opts_skip="${3}"
  local default_rsync_opts_filterd=()

  shift 3

  local rsync_opts_from_args=("${@}")

  # Known bmsu commands to skip forwarding to rsync.
  if [[ "${rsync_opts_from_args[0]:-}" =~ ^(config|restore)$ ]]; then
    rsync_opts_from_args=("${rsync_opts_from_args[@]:1}")

    local command="config_${rsync_opts_from_args[0]:-}"
    if declare -f "${command}" >/dev/null 2>&1; then
      "${command}" "${rsync_opts_from_args[1]:-}"
      exit
    fi
  fi

  default_rsync_opts+=("${default_rsync_opts_extras[@]}")

  for opt in "${default_rsync_opts[@]}"; do
    for skip_opt in "${default_rsync_opts_skip[@]}"; do
      if [[ "${opt}" == "${skip_opt}" ]]; then
        # Continue the outer loop (the next pattern).
        continue 2
      fi
    done

    default_rsync_opts_filterd+=("${opt}")
  done

  default_rsync_opts=("${default_rsync_opts_filterd[@]}")

  default_rsync_opts+=("${rsync_opts_from_args[@]}")

  # Special cases when the destination path (local or remote) is "/". Only add
  # this when not running as root. If you try to do this as a regular user
  # you'll get permission errors from rsync anyways since it can't set the
  # mtime of root owned parent directories.
  if [[ "${EUID}" != "0" ]]; then
    local target_path="${BMSU_DESTINATION}"
    [[ "${RESTORE}" == "1" ]] && target_path="${BMSU_RESTORE_PATH}"
    [[ "${target_path#*:}" == "/" ]] && default_rsync_opts+=("--no-implied-dirs")
  fi

  # If sources are files instead of directories, ensure they get deleted too.
  # We don't want this when backing up.
  if [ "${RESTORE}" == "1" ]; then
    if [[ " ${default_rsync_opts[*]} " == *" --delete"* || " ${default_rsync_opts[*]} " == *" --del "* ]]; then
      default_rsync_opts+=("--delete-missing-args")
    fi
  fi

  # Check to make sure all args (config and from the CLI) are flags, also
  # promote good habits by using the long form flag and = for values.
  for arg in "${default_rsync_opts[@]}"; do
    if [[ "${arg}" != -* || "${arg}" == "-" || "${arg}" == "--" ]]; then
      cat <<EOF >&2
${C_RED}RSYNC_OPTIONS${C_RESET}: '${arg:-[empty]}' must start with '-' and be a flag, aborting!

Tips:

- Use \`--bwlimit=RATE\` over \`--bwlimit RATE\` (set values with =)
- Prefer long flag names in general (human readability)
EOF
      exit 1
    fi
  done

  # Enforce --relative is set, this avoids false positive matches with the
  # padded spaces on both sides of the comparison, -R is included in case
  # someone sets it as a custom flag, it technically works too.
  if [[ ! " ${default_rsync_opts[*]} " == *" --relative "* && ! " ${default_rsync_opts[*]} " =~ " -R " ]]; then
    cat <<EOF >&2
${C_RED}RSYNC_OPTIONS${C_RESET}: '--relative' is missing and must be set, aborting!

This flag makes backups and restores so much more predictable. Since we're
using absolute paths this combination allows a restore to be the inverse of a
backup without any guesswork.

Consider using rsync's /./ path syntax if you're doing something where absolute
paths relative to the destination doesn't make sense, like restoring a macOS
user path (/Users/${USER}/myfiles) to Linux (/home/${USER}/myfiles).

In this case you can use "${HOME}/./myfiles" as one of your source paths instead
of using "${HOME}/myfiles". Our best friend rsync will make it "just work".
EOF

    exit 1
  fi

  if [[ " ${default_rsync_opts[*]} " == *" --no-relative "* || " ${default_rsync_opts[*]} " == *" --no-R "* ]]; then
    cat <<EOF >&2
${C_RED}RSYNC_OPTIONS${C_RESET}: '--no-relative' cannot be set, aborting!

This script doesn't allow this flag in its current form. You can remove this
validation check in the source code to allow it if it unblocks you.

Be really careful if you're performing a restore with --no-relative since it
will dump your files straight into "/" if that's your BMSU_RESTORE_PATH.

Doing this as a non-root user will protect you since you'll get permission
denied but still, it's a sketchy situation to accidentally walk into.

If you feel there's a sound use case for it, please open an issue at:

https://github.com/nickjj/bmsu
EOF

    exit 1
  fi

  if [[ " ${default_rsync_opts[*]} " == *" --restore "* ]]; then
    cat <<EOF >&2
${C_RED}RSYNC_OPTIONS${C_RESET}: '--restore' isn't a valid rsync flag, aborting!

Did you mean to run bmsu restore (without the --)?
EOF

    exit 1
  fi

}

merge_exclude_patterns() {
  local -n exclude_patterns="${1}"
  local -n exclude_patterns_extras="${2}"
  local -n exclude_patterns_skip="${3}"
  local exclude_patterns_filterd=()

  exclude_patterns+=("${exclude_patterns_extras[@]}")

  for pattern in "${exclude_patterns[@]}"; do
    for skip_pattern in "${exclude_patterns_skip[@]}"; do
      if [[ "${pattern}" == "${skip_pattern}" ]]; then
        # Continue the outer loop (the next pattern).
        continue 2
      fi
    done

    exclude_patterns_filterd+=("${pattern}")
  done

  exclude_patterns=("${exclude_patterns_filterd[@]}")
}

# This must happen before we merge because there's logic dependent on this.
RESTORE=
[ "${1:-}" == "restore" ] && RESTORE=1

merge_rsync_opts "BMSU_DEFAULT_RSYNC_OPTS" "BMSU_DEFAULT_RSYNC_OPTS_EXTRAS" "BMSU_DEFAULT_RSYNC_OPTS_SKIP" "${@}"
merge_exclude_patterns "BMSU_EXCLUDE_PATTERNS" "BMSU_EXCLUDE_PATTERNS_EXTRAS" "BMSU_EXCLUDE_PATTERNS_SKIP"

# -----------------------------------------------------------------------------
# Maybe show the config after merging everything
# -----------------------------------------------------------------------------

if [[ "${DEBUG}" == "1" || "${1:-}" == "config" ]]; then
  print_config
  [ "${1:-}" == "config" ] && exit
fi

# These are populated below, we're doing it after the config to avoid them
# being included in the output since these are internal.
BMSU_MOUNT=
BMSU_DESTINATION_ABSOLUTE=
BMSU_SOURCE_ABSOLUTE=
BMSU_RSYNC_EXCLUDE_FLAGS=()
BMSU_RSYNC_SOURCES_FLAGS=()

BMSU_DESTINATION_REMOTE=
BMSU_REMOTE_DESTINATION=
[[ "${BMSU_DESTINATION}" == *:* ]] && BMSU_DESTINATION_REMOTE=1

# -----------------------------------------------------------------------------
# Validate destination
# -----------------------------------------------------------------------------
validate_destination() {
  _validate_config_presence "BMSU_DESTINATION"
  _validate_config_string "BMSU_DESTINATION"

  # We'll allow "/" by itself or ":/" to support both root local and remote paths.
  [[ "${BMSU_DESTINATION#*:}" != "/" ]] && _validate_no_ending_forward_slash "BMSU_DESTINATION"

  # It's a remote path, not a mount.
  if [ "${BMSU_DESTINATION_REMOTE}" == "1" ]; then
    BMSU_REMOTE_DESTINATION="${BMSU_DESTINATION#*:}"

    # rsync expands the ~/ user correctly with and without the user defined.
    # This effectively disables ~user which is supported by rsync but is not
    # as common as someone putting ~some/path while forgetting the slash.
    if [[ "${BMSU_REMOTE_DESTINATION}" != /* && "${BMSU_REMOTE_DESTINATION}" != \~/* && "${BMSU_REMOTE_DESTINATION}" != \~ ]]; then
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' is an invalid format, aborting!

Valid examples for what comes after the colon:

- Starts with / to be an absolute path
- Starts with ~/some/path
- ~ by itself to be the user's home directory

When '~' is used it will expand to the remote user if you supplied the user
as part of your destination, if not, it will use ${USER} (your local user).
EOF

      exit 1
    fi
    if [[ "${BMSU_DESTINATION}" == :* ]]; then
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' is missing at least a hostname, aborting!

Include the user@host or at least the host, for example:

${USER}@somehost${BMSU_DESTINATION}
somehost${BMSU_DESTINATION}
EOF
      exit 1
    fi
  else
    # It's a local or network mount, expand the user's home directory.
    BMSU_DESTINATION="${BMSU_DESTINATION/#~/${HOME}}"

    _validate_absolute_path "BMSU_DESTINATION"

    # Linux and macOS compatible way to get the mount path from a path.
    BMSU_MOUNT=$(df -P "${BMSU_DESTINATION}" 2>/dev/null | awk 'END{print $NF}' || true)

    [ -z "${BMSU_MOUNT}" ] && _validate_path_exists "BMSU_DESTINATION"

    if [ "${BMSU_MOUNT}" == "/" ]; then
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_DESTINATION}' has no valid external mount, aborting!

Here's the output of the \`mount\` command, check the above path or your mount below for typos:

$(mount)
EOF

      exit 1
    fi

    if [ ! -w "${BMSU_MOUNT}" ]; then
      # id -gn is used instead of $USER to report correctly on Linux and macOS.
      cat <<EOF >&2
${C_RED}BMSU_DESTINATION${C_RESET}: '${BMSU_MOUNT}' mount is not writable by ${USER} (your \$USER), aborting!

Here's the output of \`ls -lad ${BMSU_MOUNT}\` and a few tips:

$(ls -lad "${BMSU_MOUNT}")

The above line should start with 'drwx' and be owned by ${USER}:$(id -gn)

If the owner is root or another user, run:
  sudo chown -R ${USER}:$(id -gn) ${BMSU_MOUNT}

If you're missing write permissions (no 'w' in the first 4 chars), run:
  chmod -R u+w ${BMSU_MOUNT}

If all else fails run the \`mount "${BMSU_MOUNT}"\` command and confirm everything looks good.
EOF

      exit 1
    fi

    mkdir -p "${BMSU_DESTINATION}"
  fi
}

# -----------------------------------------------------------------------------
# Build up exclude patterns
# -----------------------------------------------------------------------------
validate_exclude_patterns() {
  for item in "${BMSU_EXCLUDE_PATTERNS[@]}"; do
    BMSU_RSYNC_EXCLUDE_FLAGS+=("--exclude=${item}")
  done
}

# -----------------------------------------------------------------------------
# Validate and build up sources
# -----------------------------------------------------------------------------
validate_sources() {
  _validate_config_presence "BMSU_SOURCES"
  _validate_config_array "BMSU_SOURCES"

  [ "${BMSU_DESTINATION_REMOTE}" != "1" ] && BMSU_DESTINATION_ABSOLUTE="$(realpath "${BMSU_DESTINATION//\/\.\//\/}")"

  for item in "${BMSU_SOURCES[@]}"; do
    # Support expanding ~ to home.
    item="${item/#~/${HOME}}"

    # This currently limits sources to being local or network mounts, not remote
    # hosts. If remote sources is requested enough it can be added.
    _validate_no_ending_forward_slash "BMSU_SOURCES" "${item}"
    _validate_absolute_path "BMSU_SOURCES" "${item}"

    # Only validate these paths when not restoring, since they are locally checked.
    if [ "${RESTORE}" != "1" ]; then
      # rsync supports /:/ paths but we shouldn't include that when validating.
      local clean_item="${item//\/\.\//\/}"

      [[ ! -d "${clean_item}" && ! -f "${clean_item}" ]] && _validate_path_exists "BMSU_SOURCES" "${item}"

      if [ ! -r "${clean_item}" ]; then
        echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' is not readable by '${USER}', aborting!" >&2
        exit 1
      fi

      # We can only run these tests for local or network mounts, not a remote path.
      if [ "${BMSU_DESTINATION_REMOTE}" != "1" ]; then
        BMSU_SOURCE_ABSOLUTE=$(realpath "${clean_item}")

        if [ "${BMSU_SOURCE_ABSOLUTE}" == "${BMSU_DESTINATION_ABSOLUTE}" ]; then
          echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' is identical to BMSU_DESTINATION='${BMSU_DESTINATION}', aborting!" >&2
          exit 1
        fi

        if [[ "${BMSU_DESTINATION_ABSOLUTE}" == "${BMSU_SOURCE_ABSOLUTE}/"* ]]; then
          echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' is a parent of BMSU_DESTINATION='${BMSU_DESTINATION}', aborting!" >&2
          exit 1
        fi

        if [[ "${BMSU_SOURCE_ABSOLUTE}" == "${BMSU_DESTINATION_ABSOLUTE}/"* ]]; then
          echo "${C_RED}BMSU_SOURCES${C_RESET}: '${item}' is inside BMSU_DESTINATION='${BMSU_DESTINATION}', aborting!" >&2
          exit 1
        fi
      fi
    fi

    BMSU_RSYNC_SOURCES_FLAGS+=("${item}")
  done
}

# -----------------------------------------------------------------------------
# Validate and prepare restore path
# -----------------------------------------------------------------------------

validate_and_prepare_restore_path() {
  # Skip doing anything when we're not restoring.
  [ "${RESTORE}" != "1" ] && return

  _validate_config_presence "BMSU_RESTORE_PATH"
  _validate_config_string "BMSU_RESTORE_PATH"

  # Both this and the next check limit this path to being local but I think
  # that's probably a good idea to avoid accidentally restoring to a remote
  # host. I added this comment to note that this use case was considered.

  # We'll allow "/" by itself since that's an expected path.
  [ "${BMSU_RESTORE_PATH}" != "/" ] && _validate_no_ending_forward_slash "BMSU_RESTORE_PATH"

  _validate_absolute_path "BMSU_RESTORE_PATH"

  [ ! -d "${BMSU_RESTORE_PATH}" ] && _validate_path_exists "BMSU_RESTORE_PATH"

  # We always want debug mode enabled for restoring.
  DEBUG=1

  # Reset this array since we'll rebuild it with path adjustments.
  BMSU_RSYNC_SOURCES_FLAGS=()

  for source in "${BMSU_SOURCES[@]}"; do
    # Extract the "implied" part of the path. If '/./' exists, grab everything
    # after it. Otherwise, we strip the leading slash to treat the entire
    # absolute path as relative to the BMSU_DESTINATION.
    local relative_path="${source##*/./}"
    [[ "${relative_path}" == "${source}" ]] && relative_path="${source#/}"

    # Reinsert the '/./' so rsync can use it. The destination is now the source
    # since we're restoring.
    BMSU_RSYNC_SOURCES_FLAGS+=("${BMSU_DESTINATION%/}/./${relative_path}")
  done

  # Now let's restore to the restore path.
  BMSU_DESTINATION="${BMSU_RESTORE_PATH}"
}

# -----------------------------------------------------------------------------
# Prepare rsync command
# -----------------------------------------------------------------------------
prepare_rsync_command() {
  # Ensure each string and array element is colored up but not the backslashes.
  PRETTY_COMMAND=("${C_BLUE}rsync${C_RESET}"
    "${BMSU_DEFAULT_RSYNC_OPTS[@]/#/$C_CYAN}"
    "${BMSU_RSYNC_EXCLUDE_FLAGS[@]/#/$C_YELLOW}"
    "${BMSU_RSYNC_SOURCES_FLAGS[@]/#/$C_GREEN}"
    "${C_MAGENTA}${BMSU_DESTINATION}${C_RESET}")
  PRETTY_COMMAND=("${PRETTY_COMMAND[@]/%/$C_RESET}")

  COMMAND=(rsync
    "${BMSU_DEFAULT_RSYNC_OPTS[@]}"
    "${BMSU_RSYNC_EXCLUDE_FLAGS[@]}"
    "${BMSU_RSYNC_SOURCES_FLAGS[@]}"
    "${BMSU_DESTINATION}")
}

# -----------------------------------------------------------------------------
# Debug information
# -----------------------------------------------------------------------------
print_debug_info() {
  cat <<EOF
-------------------------------------------------------------------------------
FINAL RSYNC COMMAND
-------------------------------------------------------------------------------

EOF

  # Pretty print the arguments. The sed command is adding 2 spaces before each
  # argument except the first one and strips the last trailing slash. It's done
  # in a way that works on Linux and macOS.
  for arg in "${PRETTY_COMMAND[@]}"; do
    # Backslash escaping fun, this yields (1) printed backslash.
    printf "%b \\\\\n" "${arg}"
  done | sed -e "1b" -e "s/^/  /" -e '$ s/ \\$//'

  # This wouldn't be catastrophic but it's a potentially common issue to
  # bring attention to, if anything to avoid surprises and nested paths.
  if [[ "${BMSU_DESTINATION_REMOTE}" == "1" && "${RESTORE}" != "1" && "${BMSU_DESTINATION#*:}" != "/" ]]; then
    for item in "${BMSU_SOURCES[@]}"; do
      # If someone is using /./, they are controlling the path so let's skip
      # the symmetry warning for this item.
      [[ "${item}" == */./* ]] && continue

      if [[ "${item}" != "${HOME}"* ]]; then
        local dest_path="${BMSU_DESTINATION#*:}"
        local suggested_dest_path="${BMSU_DESTINATION%%:*}:/"

        cat <<EOF >&2

${C_WHITE}WARNING${C_RESET}:
Backing up ${C_GREEN}BMSU_SOURCES=${item}${C_RESET} into a remote ${C_MAGENTA}BMSU_DESTINATION${C_RESET} that is not '/'.
Your command will work but you'll end up with '${item}' nested in '${dest_path}'.
If you want symmetric paths set ${C_MAGENTA}BMSU_DESTINATION=${suggested_dest_path}${C_RESET} instead.
EOF

        break
      fi
    done
  fi

  while true; do
    printf "\nTo run the above command, type 'y' and press enter (y/n) "
    read -r yn

    case "${yn}" in
    [Yy]*)
      break
      ;;
    [Nn]*) exit ;;
    *) printf "Please answer y or n\n" ;;
    esac
  done

  cat <<EOF

-------------------------------------------------------------------------------
RSYNC OUTPUT
-------------------------------------------------------------------------------

EOF
}

validate_destination
validate_exclude_patterns
validate_sources
validate_and_prepare_restore_path
prepare_rsync_command
[ "${DEBUG}" == "1" ] && print_debug_info

# Finally, let's run rsync!
time "${COMMAND[@]}"
