name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "master"
  schedule:
    - cron: "30 12 * * *"

jobs:
  test:
    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0

      - name: "Linting and formatting"
        run: |
          ./run ci:quality

      - name: "Tests"
        run: |
          ./run ci:test
